services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: campus_connect
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
